# Visualisation

mesh_files:
  base:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10e/visual/base/model.gltf
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10e/collision/base.obj

  shoulder:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10e/visual/shoulder/model.gltf
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10e/collision/shoulder.obj

  upper_arm:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10e/visual/upperarm/model.gltf
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10e/collision/upperarm.obj
      mesh_files:

  forearm:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10e/visual/forearm/model.gltf
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10e/collision/forearm.obj

  wrist_1:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10e/visual/wrist1/model.gltf
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10e/collision/wrist1.obj
    visual_offset: -0.135

  wrist_2:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10e/visual/wrist2/model.gltf
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10e/collision/wrist2.obj
    visual_offset: -0.12

  wrist_3:
    visual:
      mesh:
        package: ur_description
        path: meshes/ur10e/visual/wrist3/model.gltf
      material:
        name: "LightGrey"
        color: "0.7 0.7 0.7 1.0"
    collision:
      mesh:
        package: ur_description
        path: meshes/ur10e/collision/wrist3.obj
    visual_offset: -0.1168
